include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    document_ignores: ignore
    todo: ignore
  exclude:
    - flutter/**

linter:
  rules:
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_const_declarations: true
